name: Build and Test

on:
  push:
    branches:
      - '*'
      - '!v*'
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust x86_64-unknown-linux-gnu
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-unknown-linux-gnu
          profile: minimal
      
      - name: Install Rust wasm32-unknown-unknown
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown
          profile: minimal

      - name: Install Trunk CLI
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: trunk --locked

      - name: Install Tauri CLI
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: tauri-cli --locked

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build

      